{
 "title": "Stock v0.1.2",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "number",
    "label": "股票代码",
    "query": "SELECT DISTINCT code FROM stock.stock_price"
   },
   { "name": "heatSource", "label": "热点全追踪", "query": "东方财富,雪球" }
  ]
 },
 "panels": [
  { "title": "A 股市场全知道", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$number: K 线图",
   "type": "candlestick",
   "description": "洞察市场价格",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "stock",
     "rawSql": "SELECT * FROM stock.stock_price WHERE code = \"$number\";"
    }
   ]
  },
  {
   "title": "$number: 相关热点新闻",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "dataset": "stock",
     "rawSql": "SELECT 发布时间, 新闻标题 FROM stock.stock_news_individual where 关键词 = $number LIMIT 50"
    }
   ]
  },
  {
   "title": "$number: 相关热点新闻",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "dataset": "stock",
     "rawSql": "SELECT 发布时间, 新闻标题 FROM stock.stock_news_individual where 关键词 = $number LIMIT 50"
    }
   ]
  },
  {
   "title": "热点：$heatSource",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "stock",
     "rawSql": "SELECT * FROM stock.$heatSource LIMIT 20;"
    }
   ]
  },
  {
   "title": "热点板块全追踪",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT 所属板块名称,股票名称,涨跌幅,综合热度,市场代码 FROM stock.stock_hot_search LIMIT 50 "
    }
   ]
  },
  {
   "title": "其他热点新闻",
   "type": "table",
   "description": "洞察市场热点新闻",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "dataset": "stock",
     "rawSql": "SELECT * FROM stock.stock_news_real LIMIT 50 "
    }
   ]
  }
 ]
}